public class BuilderDemo {
    public static void main(String[] args) {
        System.out.println("--- Creational: Builder (Report) ---");
        ReportBuilder builder = new SimpleReportBuilder()
                .withHeader("Sales Report Q3")
                .withBody("- Revenue: $1.2M\n- Units Sold: 25k")
                .withFooter("Generated by ReportBuilder");

        Report report = builder.build();
        System.out.println(report.render());
    }
}
